name: Copilot Automatic Deboarder
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 28 * *" # 28th of every month at 20:00
env:
  MAX_DAYS_INACTIVE: 90
permissions:
  contents: read
jobs:
  deboard:
    name: Deboard process
    runs-on: ubuntu-latest
    steps:
      - name: Fulfill
        uses: MartinTesterAtWork/copilot-issueops/.github/deboardCopilot@main
        with:
          application-id: ${{ secrets.ONBOARDER_APP_ID }}
          application-private-key: ${{ secrets.ONBOARDER_APP_PK }}